set nocompatible
filetype indent plugin on
syntax on
set hidden
set wildmenu
set showcmd
set hlsearch
set ignorecase
set smartcase
set backspace=indent,eol,start
set autoindent
set nostartofline
set ruler
set laststatus=2
set confirm
set shiftwidth=4
set softtabstop=4
set expandtab
set colorcolumn=60
set list
set listchars=
set relativenumber
set showcmd
set title
set hidden     
set nowrap
set autoindent
set noswapfile
