set nocompatible
filetype indent plugin on
syntax on
set hidden
set wildmenu
set hlsearch
set ignorecase
set smartcase
set backspace=indent,eol,start
set autoindent
set nostartofline
set ruler
set confirm
set shiftwidth=4
set softtabstop=4
set expandtab
set relativenumber
set showcmd
set title
set nowrap
set noswapfile
